### ISSUE TITLE
Unable to add course on xk.autoisp.shu.edu.cn:8084

### ISSUE THREAD

**Issue by missfdu** [ZKLlab/SHU-scheduling-helper#6]
![image](https://user-images.githubusercontent.com/52066631/71554395-6b5e0080-2a59-11ea-8c17-a06ec29fe4bd.png)
如图，在[上海大学本硕博一体化选课系统](xk.autoisp.shu.edu.cn:8084)上查询冬季学期的课程时，排课助手那一栏空白，不显示添加课程的按钮，无法添加至排课助手中。
感谢开发者的付出！

**Comment by ZKLlab** [comment]
谢谢你的反馈！已添加对课程查询页面的支持，新的Pre-release已经发布，请试用：[v0.3.0-beta.2](https://github.com/ZKLlab/SHU-scheduling-helper/releases/tag/v0.3.0-beta.2)
